### ISSUE TITLE
Displaying incorrect balance when fetching RGB++ balance via BTC address

### ISSUE THREAD

**Issue by Dawn-githup** [ckb-cell/btc-assets-api#202]
### Description

**Preconditions:**
- The total amount of 999 tokens is in the same UTXO.
- Leap 500 xudt.
- The BTC transaction is unconfirmed.
```jsx
Check: https://api.testnet.rgbpp.io/rgbpp/v1/address/tb1qt7gg5um02gj7yw0khdnsmzlqpqmcdz87zpvnh9/balance

{
  "address": "tb1qt7gg5um02gj7yw0khdnsmzlqpqmcdz87zpvnh9",
  "xudt": [
    {
      "name": "XUDT Test Token",
      "decimal": 8,
      "symbol": "FGG",
      "total_amount": "0xb9e459300",
      "available_amount": "0x0",
      "pending_amount": "0xb9e459300",
      "type_hash": "0xa5a802e130d41ed668d484e85ec6343ad58460f65fa319255e4fdad32ed5f64d",
      "type_script": {
        "codeHash": "0x25c29dc317811a6f6f3985a7a9ebc4838bd388d19d0feeecf0bcd60f6c0975bb",
        "args": "0x031933877ecd5ed36ea1db7d497d7d06a62ac1a68df3435c460357b319fe4e77",
        "hashType": "type"
      }
    }
  ]
}
```

**Issues:**
1. The `total_amount` should display as 999 but currently shows 499.
2. The `pending_amount` should display as 500 but currently shows 499.

**Comment by ShookLyngs** [comment]
> The `pending_amount` should display as 500 but currently shows 499.

I feel like the `pending_amount` field should represent the unconfirmed balance of a XUDT asset. If 500 out of 900 tokens are being transferred and the transaction pair is not confirmed on-chain, the `pending_amount` should be 499 instead of 500.

@Flouse @ahonn any thoughts?

**Comment by Flouse** [comment]
> the `pending_amount`

Yes, I think the sender's pending_amount should be (999 - 500 = 499).
